jwt:
  secret_key: "secret"
grpc:
  address: ":9090"
http:
  address: ":8080"
  host: "localhost"
  port: "8080"
  read_timeout: "10s"
  write_timeout: "10s"
  allowed_origins: ["http://localhost:8083"]
  webhook_handler_endpoint: "/api/webhook-callback"
payment_system:
  create_endpoint: "localhost:8083/api/http"
postgres:
  dsn: "postgresql://postgres:123@localhost:5432/postgres?sslmode=disable"
  max_connections: 25
  max_idle_connections: 10
  conn_max_lifetime: "30m"
  conn_max_idle_time: "5m"
kafka:
  address: "localhost:9092"
  topic: "my-topic"