services:
        
  booking-postgres:
    image: postgres:16-alpine
    container_name: booking-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: booking
    volumes:
      - booking-postgres-data:/var/lib/postgresql/data
    networks:
      - booking-network
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  booking-service:
    build: ./booking_service
    container_name: booking-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./booking_service/config.yml:/app/config.yml
      - ./booking_service/migrations:/app/migrations
    depends_on:
      - booking-postgres
    networks:
      - booking-network
    command: ["./app"]
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  booking-prometheus:
    image: prom/prometheus:v3.8.0
    container_name: booking-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./booking_service/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - booking-network

  booking-grafana:
    image: grafana/grafana:12.3.0
    container_name: booking-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - booking-prometheus
    networks:
      - booking-network

  payment-service:
    build: ./payment_service
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    volumes:
      - ./payment_service/config.yml:/app/config.yml
    networks:
      - booking-network
    command: [ "./app" ]
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

  hotel-postgres:
      image: postgres:16-alpine
      container_name: hotel-postgres
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: hotels_data
      volumes:
        - hotel-postgres-data:/var/lib/postgresql/data
      networks:
        - booking-network
      logging:
        driver: "local"
        options:
          max-size: "10m"
          max-file: "3"

  hotel-service:
    build: ./hotel_service
    container_name: hotel-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - ./hotel_service/config.yml:/app/config.yml
      - ./hotel_service/migrations:/app/migrations
    depends_on:
      - hotel-postgres
    networks:
      - booking-network
    command: ["./app"]
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  booking-postgres-data:
  hotel-postgres-data:
  prometheus-data:
  grafana-data:
  kafka-data:

networks:
  booking-network:
