syntax = "proto3";

package hotel;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/mihaillepenkin/MTSGolangProjectBooking/protos/gen/hotel;hotel";

service Hotel {
  rpc BlockRoomAvailability(BlockRoomRequest) returns (BlockRoomResponse);
  rpc IsRoomAvailable(IsRoomAvailableRequest) returns (IsRoomAvailableResponse);
  rpc IsHotelier(IsHotelierRequest) returns (IsHotelierResponse);
}

message BlockRoomRequest {
  string hotelName = 1; // Name of the hotel
  string roomNumber = 2; // Number of the room
  google.protobuf.Timestamp start = 3; // Start of the blocking interval [start, end)
  google.protobuf.Timestamp end = 4; // End of the blocking interval
}

message BlockRoomResponse {
  string info = 1; // Some info, maybe empty
}

message IsRoomAvailableRequest {
  string hotelName = 1; // Name of the hotel
  string roomNumber = 2; // Number of the room
  google.protobuf.Timestamp start = 3; // Start of the interval [start, end) to check
  google.protobuf.Timestamp end = 4; // End of the interval to check
}

message IsRoomAvailableResponse {
  bool isAvailable = 1;
}

message IsHotelierRequest {
  string hotelName = 1; // Name of the hotel
  string userID = 2; // ID to check for hotelier
}

message IsHotelierResponse {
  bool isHotelier = 1;
}